version: "3.9"
services:
  web:
    build:
      context: .
    image: webapp:2.0
    ports:
      - "80:5000"
    restart: always
    links:
    - redis
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BIND_PORT=80:5000
  redis:
    image: "redis:alpine"
    expose: 
      - 6379
networks:
  webnet: