apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort #LoadBalancer better for production environment
  selector:
    app: redis
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 5000
    #nodePort could be selected automatically when you create the service